export const API_ENDPOINTS = {
  auth: {
    login: '/auth/iniciar-sesion',
    register: '/auth/registrar',
    me: '/auth/me',
    refresh: '/auth/renovar-token',
    logout: '/auth/cerrar-sesion',
    recoverPassword: '/auth/recuperar-contrasena',
    verifyCode: '/auth/verificar-codigo',
    resetPassword: '/auth/restablecer-contrasena',
  },
  predenuncias: '/predenuncias',
  casos: '/casos',
  asignaciones: '/asignaciones',
  denuncias: '/denuncias',
  seguimientos: '/seguimientos',
  citas: '/citas',
  reportes: '/reportes',
  notificaciones: '/notificaciones',
  misNotificaciones: '/notificaciones/me',
  usuarios: '/usuarios',
  usuarioPerfil: '/usuarios/me',
  usuarioCambiarContrasena: '/usuarios/me/contrasena',
  adjuntos:'/evidencias',
  victimas: '/victimas',
  victimaHistorial: '/victimas/me/historial',
  panelPrincipal: '/panel-principal/me',
} as const;
